version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./MSharp.Modals.sln && dotnet publish ./MSharp.Modals.sln -c Release -o ./obj/Docker/publish"
